.TH "faxg4coder" 1 0.2 "20 Oct 2023" "User Manual"

.SH NAME
faxg4coder

.SH DESCRIPTION
G3/G4 Fax En-/Decoder.

.SH SYNOPSIS
faxg4coder [options] [infile] [outfile]

.SH OPTIONS
.TP
-g3
G3 1-dimensional code (default)
.TP
-g3{K}
G3 2-dimensional code, parameter {K}, e.g. -g32 for K=2
.TP
-g4
G4 (2-dim) code
.TP
-hdr
Put/Read MMR header to file
.TP
-decode{W}
Decode to pbm-file, using image width {W}, e.g. -decode1728 (default, if not given), else : encode from pbm-file
.TP
-p
Write plain pbm
.TP
-b
Read/Write bitstrings
.TP
-h
Show help

Only K=2 (low resolution) and K=4 (high resolution) are standardized.
If outfile or both infile and outfile are not given
standard output and maybe standard input are used.


.SH EXAMPLE
 faxg4coder -g4 page.pbm page.g4
 faxg4coder -g4 -decode2480 page.g4 page.pbm

 faxg4coder -g4 -hdr page.pbm page.g4whdr
 djvumake page.djvu Smmr=page.g4whdr

.SH COPYRIGHT
GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007

.SH SEE ALSO
 faxlzwcoder(1)

.SH CONTACTS
Website:
 https://github.com/ImageProcessing-ElectronicPublications/faxcoder
